### ISSUE TITLE
Logo Danake

### ISSUE THREAD

**Issue by donatelloferraz** [donatelloferraz/Danake#13]
![12170252_872499862868906_1069571484_n](https://cloud.githubusercontent.com/assets/6604658/10614286/202a8882-7738-11e5-9e5e-ce674c06bd0a.jpg)

**Comment by donatelloferraz** [comment]
Otra opção 
![12170252_872499862868906_1069571484_n](https://cloud.githubusercontent.com/assets/6604658/10614286/202a8882-7738-11e5-9e5e-ce674c06bd0a.jpg)

**Comment by donatelloferraz** [comment]
Logo feito por @Brayan1

**Comment by donatelloferraz** [comment]
@Brayan1  Coloca o logotipo feito por você no Read Me https://github.com/donatelloferraz/Danake/blob/master/README.md
e também como Sidebar
https://github.com/donatelloferraz/Danake/wiki/_new?wiki%5Bname%5D=_Sidebar

**Comment by Brayan1** [comment]
Tarefa Concluída. Qualquer coisa é só avisar!

**Comment by donatelloferraz** [comment]
Ficou ótimo.
