### ISSUE TITLE
Tela de login

### ISSUE THREAD

**Issue by donatelloferraz** [donatelloferraz/Danake#7]
Tela de login com designer clean e responsivo

**Comment by donatelloferraz** [comment]
Irei começar a trabalhar com a tela de login. 
E tentar criar o index, só que dessa vez totalmente através de um script em C.. 
Tentarei procurar um css interessante. E a implementação do login do Facebook.

**Comment by GeorgeCandido** [comment]
Criado hangouts hoje para melhoria do código fonte da tela index.html, retirado o html do arquivo e incorporado no projeto em C (alterações a serem commitadas pelo Donatello no GitHub).

Participantes do hangouts: Adalton(Donatello), Brayan Rocha, Dione Max, George Cândido.

**Comment by donatelloferraz** [comment]
Fiz o Pull, agora temos que buscar uma solução para nosso método de scripts.
